### ISSUE TITLE
3 active accounts set but 2 playing

### ISSUE THREAD

**Issue by boundir** [demen10/MBR_Mod#1]
So, here is the context:

Using 4.5.0, botting 3 accounts with MEmu. There are 7 accounts on that instance of MEmu.

- Profile 1 to Acc 3

- Profile 2 to Acc 7

- Profile 3 to Acc 5

Problem is only Profile 2 & 3 are actually attacking. My guess is that 2 & 3 are set to -999 after switching.
But I don't get why they are set to -999.

Attached is a capture from the Profile Stats with the -999 thing.
![chrome_2017-07-29_12-02-33](https://user-images.githubusercontent.com/30468080/28743996-db7c5a52-7457-11e7-9a49-960d94890786.png)

**Comment by demen10** [comment]
Hi boundir,
-999 minutes are set to the active accounts that have not taken their first switch. If the bot has not switch to an account and thus not read remain train time of this account, it will assign -999 to this account.

Can you try restart the bot or stop/start when it gets messed up somehow.

**Comment by boundir** [comment]
Stop/Restart doesn't work. It reset only if I close the bot and relaunch again.
Doing that now and will try to catch when it gets messed up again.

**Comment by boundir** [comment]
Here are two logs from this morning.
We can see in the first one that it is set correctly:

```
L [2017-07-29 10:13:30.619] Start SwitchAcc
L [2017-07-29 10:13:34.084] Troops time: 12.00 min
L [2017-07-29 10:13:34.145] Profile [1] - MyVillage1 (Acc. 2) will have full army in:12 minutes
L [2017-07-29 10:13:34.146] Profile [3] - MyVillage2 (Acc. 4) was ready:6.23 minutes ago
L [2017-07-29 10:13:34.147] Profile [4] - MyVillage3 (Acc. 1) was ready:1.39 minutes ago
L [2017-07-29 10:13:34.219] Switch to active Profile [3] - MyVillage2 (Acc. 4)
```
In the second one army is ready and it goes straight to Switching account, not checking which one it should switch to.
```
L [2017-07-29 10:16:48.882] Total Army Camp capacity: 220/220 (100%)
L [2017-07-29 10:16:51.248]  - 28 Balloons Available
L [2017-07-29 10:16:51.261]  - 10 Minions Available
L [2017-07-29 10:16:51.263]  - 2 Lava Hounds Available
L [2017-07-29 10:16:51.397]  - Barbarian King available
L [2017-07-29 10:16:51.586] Total Spell(s) Capacity: 9/9
L [2017-07-29 10:16:52.303]  - 4 Rage Spells Brewed
L [2017-07-29 10:16:52.318]  - 1 Haste Spell Brewed
L [2017-07-29 10:16:52.534] Total Clancastle Spells: 1/1
L [2017-07-29 10:16:52.763]  - Haste
L [2017-07-29 10:16:52.893] Chief, is your Army ready for the battle? No, not yet!
L [2017-07-29 10:16:52.895]  - CC Troops are not Ready!
D [2017-07-29 10:16:57.019] BotShrinkExpandToggle: Bot collapsed
L [2017-07-29 10:17:10.205] Requesting Clan Castle Troops
D [2017-07-29 10:17:10.709] CheckBotZOrder: Ajust windows Z Order for standard window
L [2017-07-29 10:17:20.391] Time Idle: 00:01:02
L [2017-07-29 10:17:20.401] Still waiting for CC troops/ spells, switching to another Account
L [2017-07-29 10:17:20.403] Switch to active Profile [4] - MyVillage3 (Acc. 1)
```
And the same goes for MyVillage3
```
L [2017-07-29 10:21:03.225] Total Army Camp capacity: 180/200 (90%)
L [2017-07-29 10:21:04.820]  - 70 Barbarians Available
L [2017-07-29 10:21:04.828]  - 65 Archers Available
L [2017-07-29 10:21:04.829]  - 9 Giants Available
L [2017-07-29 10:21:04.865] Troops time: 2.00 min
L [2017-07-29 10:21:04.911]  - Barbarian King available
L [2017-07-29 10:21:05.049] Total Spell(s) Capacity: 7/7
L [2017-07-29 10:21:05.703]  - 3 Lightning Spells Brewed
L [2017-07-29 10:21:05.705]  - 1 Poison Spell Brewed
L [2017-07-29 10:21:05.871] Chief, is your Army ready for the battle? No, not yet!
L [2017-07-29 10:21:05.872]  - Troops are not Ready!
D [2017-07-29 10:21:14.548] AdbScreencap: 170/206/265 ms (all/10/1),218,0,l=35,t=196,w=45,h=18, D7D11567AA87A6C7529D5E86C47CDEB8221563AF: w=860,h=732,f=1
L [2017-07-29 10:21:20.355] Requesting Clan Castle Troops
L [2017-07-29 10:21:30.580] Time Idle: 00:00:50
L [2017-07-29 10:21:30.581] Still waiting for CC troops/ spells, switching to another Account
L [2017-07-29 10:21:30.584] Switch to active Profile [3] - MyVillage2 (Acc. 4)
```
Never switching back to MyVillage1.

I had to zip the 3 logs. Renamed it for a better understanding.
[Logs.zip](https://github.com/demen10/MBR_Mod/files/1185049/Logs.zip)

**Comment by demen10** [comment]
I read your logs and they seem to be working correctly:

1.  At 10:13:34:
     MyVillage1's Troops time: 12.00 min, 
     MyVillage2's troop time is -6.23 min, 
     MyVillage3's troop time is -1.39 min 
     The Bot switch to MyVillage2 

2.  At 10:17:20:
     MyVillage2's troop time is -6.23 - 4 = -10.23 minutes, but CC troops/ spells are not ready
     MyVillage1's Troops time: 12.00 - 4 = 6 min, 
     MyVillage3's troop time is -1.39 - 4 = -5.39 min 
     The Bot switch to MyVillage3 as MyVillage2 is still wait for CC troops and no one knows when CC is full.

3.  At 10:21:30:
     MyVillage3' troop time is newly read as 2 minutes (maybe it donated some troops or you interfered to the game). Anyway, CC troops/spells are not ready.
     MyVillage2's troop time is -6.23 - 8 = -14.23 minutes
     MyVillage1's Troops time: 12.00 - 8 = 2 min, 

     The Bot switch to active MyVillage2 as MyVillage3 is still wait for CC troops. As the troop times of MyVillage2 and MyVillage3 are always less than MyVillage1's troop time so the Bot will jump between MyVillage2 and MyVillage3 until 1 account gets its attack and reset its trooptime to be greater than MyVillage1's.

In next release, I will and a condition that "ForceSwitch when Wait for CC" will only be activated in "SmartSwitch". "Normal Switch" will keep switching continuously no matter what.

Or you can add this hot fix at line 912 of MyBot.Run.au3 as follows:
			If $ichkSwitchAcc = 1 Then _; SwitchAcc Demen_
				If $g_bWaitForCCTroopSpell **_And $ichkSmartSwitch = 1_** Then
					Setlog("Still waiting for CC troops/ spells, switching to another Account")
					ForceSwitchAcc($eDonate)
				Else
					checkSwitchAcc()
				EndIf
			Else
				SmartWait4Train()
			EndIf

**Comment by boundir** [comment]
With the hotfix applied :

```

**Comment by boundir** [comment]
Confirmed working with this fix. Good job!

**Comment by demen10** [comment]
Thanks for your support. Happy botting!
